### ISSUE TITLE
force close bot

### ISSUE THREAD

**Issue by bimopraksw** [monteksz/pixelverse#2]
![Screenshot 2024-06-24 193441](https://github.com/monteksz/pixelverse/assets/114793651/f087a4f8-2d25-4d3b-bf94-c270427ed07f)

abis email sementara berhasil dibuat langsung Gagal mengirim permintaan OTP.

**Comment by bimopraksw** [comment]
![Uploading Screenshot 2024-06-24 194236.png…]()

**Comment by bimopraksw** [comment]
![Screenshot 2024-06-24 194236](https://github.com/monteksz/pixelverse/assets/114793651/6882bd7d-ff90-4b51-86d0-486d888424ac)

**Comment by monteksz** [comment]
mati domain emailnya kena tebas, lagi nyari temp mail yang work

**Comment by bimopraksw** [comment]
mungkin InstAddr bisa, semangat bang montekz im counting on you <3
